[package]
name = "real_estate"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmwasm-std = { version = "1.0.0", default-features = false }
cosmwasm-storage = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8.0"
serde_json = "1.0.64"
thiserror = "1.0"
cw2 = "0.10.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["iterator"]
iterator = ["cosmwasm-storage/iterator"]
